### PR TITLE
Fixes all bugs and simplifies the code.

### PR DESCRIPTION
**Pull request by specialunderwear**
Hey bennie, I changed everything a lot.
And it's not done yet as well.

But maybe you can help me with 1 things I dont understand:

1. what is
    ```
    parser.add_argument('--bdist',
                        help="Creates an additional source distribution and its dependencies",
                        action='store_true',
                        default=False)
    ```
    for exactly?

So what bugs did I fix heh?

1. Dependencies are always declared as '>=' in de deb even if you got < in setup.py
2. Not all dependencies get built
3. Packages not present in the buildout versions file are not built at all

### CODE REVIEW

**Comment by specialunderwear** [comment]
O Bennie, most of the code that was in this package is moved to vdt.versionplugin.debianize. So the code that makes sure pyyaml gets a sane package name is in there.

I also removed the depency on the shell script debianize.sh, everything is now pure python. I just use pip to download all the tar balls and then build with fpm.

**Comment by specialunderwear** [comment]
The way the plugin works is that it makes sure that the version pinned in buildout is downloaded.
It doesn't actually change the way your dependency is specified. That means that if you had 'koe>1.0' in setup.py it will become koe (>>1.0) in de deb. If you pinned the version of koe in buildout to 2.0, then that is the package that will be built by the plugin.

**Comment by benjamin-beermann** [comment]
Hi Lars thx for your effort. The --bdist additionally builds an additional binary distribution (e.g. wheel) besides the debian package. Give me some time to check your changes, because several of our products depend on vdt.buildout.

**Comment by specialunderwear** [comment]
Ok I just noticed you had tests 😄 those are all broken now, sorry.

**Comment by specialunderwear** [comment]
Btw martijn has built a buildout recipe for vdt.version and you can also use it to build wheels. (It uses vdt.versionplugin.wheel in that case. You need to build the deb and the wheel separately in that case. I don't know if you can live with that.

**Comment by benjamin-beermann** [comment]
But does vdt.versionplugin.wheel also fix names? You should not fix my tests but add tests for your changes ;D

**Comment by specialunderwear** [comment]
Yes it fixes the names, but I moved it into vdt.versionplugin.debianize

**Comment by specialunderwear** [comment]
Look here is the code: https://github.com/devopsconsulting/vdt.versionplugin.debianize/blob/master/vdt/versionplugin/debianize/shared.py#L100

**Comment by benjamin-beermann** [comment]
Ok but the wheel recipe does not pin versions right?

**Comment by specialunderwear** [comment]
right

**Comment by specialunderwear** [comment]
But you don;t need to build the dependencies if you build a wheel or do you?

**Comment by benjamin-beermann** [comment]
We build a wheel for our package and also for their dependencies right now

**Comment by specialunderwear** [comment]
with fpm? or with python-wheel?

**Comment by specialunderwear** [comment]
I think we could override -t python so it will run python setup.py bdist_wheel instead of fpm for the wheels case. But for the package itself it would still need the trick in vdt.versionplugin.wheel to override the version from setup.py

**Comment by benjamin-beermann** [comment]
We run "python setup.py bdist_wheel --dist-dir=os.getcwd

**Comment by specialunderwear** [comment]
I do think it is a bit weird to have it build extra packages with the --bdist parameter. Better to implement -t python (I have allready implemented -t to restrict the types of packages that can be built)

**Comment by benjamin-beermann** [comment]
You are right, the --bdist argument was a hotfix back then and is definitely in the wrong place. But does -t build also the dependencies of our packages?

**Comment by specialunderwear** [comment]
-t is where you specify what the target is, eg. deb, rpm, python. Right now python has not been implemented, but for the supported targets alls dependencies are built

**Comment by specialunderwear** [comment]
This is how I fix the dependency names in all the control files, it is installed as a console_script and used as the EDITOR for editing the control file when running fpm with -e : https://github.com/devopsconsulting/vdt.versionplugin.debianize/blob/master/vdt/versionplugin/debianize/fpmeditor.py

**Comment by specialunderwear** [comment]
I will be testing the whole whing with martijn his buildout recipe in all the projects I am working on atm.
So I will report on how it goes and if there are bugs I will update.

**Comment by benjamin-beermann** [comment]
So the approach with the editor replaces my ugly approach of maintaining a static naming conversion list?

**Comment by benjamin-beermann** [comment]
Ah no its still in there

**Comment by specialunderwear** [comment]
Yeah but it is not hard to make it overridable with some file now. This approach is a bit better because I don't need to manually specify all dependencies with fpm, which requires a lot of parsing and a lot of code. I just replace the names from the dictionary with a somewhat strictly matching regex in the control file after it is generated unmodified by fpm wit all the default flags. That means any recommended packages or references in descriptions also get fixed.

**Comment by specialunderwear** [comment]
or obsoletes or replaces or any of that stuff

**Comment by specialunderwear** [comment]
@benjamin-beermann look what the cat dragged in: https://github.com/specialunderwear/vdt.versionplugin.buildout/pull/2/files

**Comment by specialunderwear** [comment]
soon ...

**Comment by benjamin-beermann** [comment]
Hahaha funny, I recently was wondering what the state is here. Looks nice! Don't forget to write tests ;b

**Comment by specialunderwear** [comment]
tests   <-- There you go

**Comment by benjamin-beermann** [comment]
Can't find any tests sneaky cat ;b

**Comment by specialunderwear** [comment]
well look about 3 lines above, before the arrow, it says "tests"

**Comment by specialunderwear** [comment]
and i wrote it

**Comment by benjamin-beermann** [comment]
Hahaha. Honestly, you don't plan to write some?

**Comment by specialunderwear** [comment]
Can you get on skype for a moment?

**Pull request merged**
